# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('list_name', models.CharField(max_length=100, unique=True, verbose_name='List name')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('subject', models.CharField(max_length=200, verbose_name='Email Subject')),
                ('content_type', models.IntegerField(choices=[(0, 'Text'), (1, 'HTML content'), (2, 'From URL')], default=0, verbose_name='Content type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL content')),
                ('email_from', models.EmailField(max_length=100, verbose_name='From')),
                ('bcc', models.ManyToManyField(help_text='Staff users who will receive BCC email', related_name='bcc_in_news', to=settings.AUTH_USER_MODEL, verbose_name='BCC')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.ContactList', verbose_name='List to send email')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_lists',
            field=models.ManyToManyField(related_name='contacts', to='newsletters.ContactList'),
        ),
    ]
