from django.utils.translation import ugettext_lazy as _

# EMAIL TYPES
EMAIL_TYPE_TEXT = 0
EMAIL_TYPE_HTML = 1
EMAIL_TYPE_URL = 2

EMAIL_TYPE_TEXT_DESCRIPTION = _(u'Text')
EMAIL_TYPE_HTML_DESCRIPTION = _(u'HTML content')
EMAIL_TYPE_URL_DESCRIPTION = _(u'From URL')

EMAIL_TYPE_CHOICES = (
    (EMAIL_TYPE_TEXT, EMAIL_TYPE_TEXT_DESCRIPTION),
    (EMAIL_TYPE_HTML, EMAIL_TYPE_HTML_DESCRIPTION),
    (EMAIL_TYPE_URL, EMAIL_TYPE_URL_DESCRIPTION)
)
